/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareDocumentIdRouteImport } from './routes/share.$documentId'
import { Route as PublicDocumentIdRouteImport } from './routes/public.$documentId'
import { Route as DuplicateDocumentIdRouteImport } from './routes/duplicate.$documentId'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareDocumentIdRoute = ShareDocumentIdRouteImport.update({
  id: '/share/$documentId',
  path: '/share/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDocumentIdRoute = PublicDocumentIdRouteImport.update({
  id: '/public/$documentId',
  path: '/public/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicateDocumentIdRoute = DuplicateDocumentIdRouteImport.update({
  id: '/duplicate/$documentId',
  path: '/duplicate/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/upload': typeof ApiUploadRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/duplicate/$documentId': typeof DuplicateDocumentIdRoute
  '/public/$documentId': typeof PublicDocumentIdRoute
  '/share/$documentId': typeof ShareDocumentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/upload': typeof ApiUploadRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/duplicate/$documentId': typeof DuplicateDocumentIdRoute
  '/public/$documentId': typeof PublicDocumentIdRoute
  '/share/$documentId': typeof ShareDocumentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/upload': typeof ApiUploadRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/duplicate/$documentId': typeof DuplicateDocumentIdRoute
  '/public/$documentId': typeof PublicDocumentIdRoute
  '/share/$documentId': typeof ShareDocumentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/upload'
    | '/documents/$documentId'
    | '/duplicate/$documentId'
    | '/public/$documentId'
    | '/share/$documentId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/upload'
    | '/documents/$documentId'
    | '/duplicate/$documentId'
    | '/public/$documentId'
    | '/share/$documentId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/upload'
    | '/documents/$documentId'
    | '/duplicate/$documentId'
    | '/public/$documentId'
    | '/share/$documentId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiUploadRoute: typeof ApiUploadRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  DuplicateDocumentIdRoute: typeof DuplicateDocumentIdRoute
  PublicDocumentIdRoute: typeof PublicDocumentIdRoute
  ShareDocumentIdRoute: typeof ShareDocumentIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$documentId': {
      id: '/share/$documentId'
      path: '/share/$documentId'
      fullPath: '/share/$documentId'
      preLoaderRoute: typeof ShareDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$documentId': {
      id: '/public/$documentId'
      path: '/public/$documentId'
      fullPath: '/public/$documentId'
      preLoaderRoute: typeof PublicDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicate/$documentId': {
      id: '/duplicate/$documentId'
      path: '/duplicate/$documentId'
      fullPath: '/duplicate/$documentId'
      preLoaderRoute: typeof DuplicateDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiUploadRoute: ApiUploadRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  DuplicateDocumentIdRoute: DuplicateDocumentIdRoute,
  PublicDocumentIdRoute: PublicDocumentIdRoute,
  ShareDocumentIdRoute: ShareDocumentIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
